# -*- coding: utf-8 -*-
"""CarMarketAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXaVrrMfnWf6OqEWQyQwKoNc4Gx5DCHJ
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
CHARTS_DIR = 'charts/'

uploaded = files.upload()

filename = next(iter(uploaded))

# Read the uploaded CSV
df = pd.read_csv(filename)

print("Shape:", df.shape)
print("\nColumns:", list(df.columns))
print("\nMissing values:\n", df.isnull().sum())
print("\nSummary statistics:\n", df.describe(include="all"))

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files



plt.figure(figsize=(10, 5.5))
plt.hist(df["Selling_Price"], bins=25, edgecolor="white")
plt.title("Distribution of Used-Car Selling Prices")
plt.xlabel("Selling Price (lakh)")
plt.ylabel("Number of Cars")
plt.tight_layout()
plt.savefig("01_selling_price_distribution.png", dpi=200)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files



plt.figure(figsize=(9, 5.5))
for fuel, g in df.groupby("Fuel_Type"):
    plt.scatter(g["Present_Price"], g["Selling_Price"], label=fuel, s=35)
coef = df[["Present_Price", "Selling_Price"]].corr().iloc[0,1]
x = pd.Series([df["Present_Price"].min(), df["Present_Price"].max()])
slope, intercept = __import__("numpy").polyfit(df["Present_Price"], df["Selling_Price"], 1)
plt.plot(x, slope*x + intercept, linewidth=2, label="Trend line")
plt.title(f"Present Price vs Selling Price (r = {coef:.2f})")
plt.xlabel("Present Price (lakh)")
plt.ylabel("Selling Price (lakh)")
plt.legend()
plt.tight_layout()
plt.savefig("02_present_vs_selling.png", dpi=200)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files



avg = df.groupby("Year")["Selling_Price"].mean()
plt.figure(figsize=(10, 5.5))
plt.plot(avg.index, avg.values, marker="o")
plt.title("Average Selling Price by Manufacturing Year")
plt.xlabel("Manufacturing Year")
plt.ylabel("Average Selling Price (lakh)")
plt.grid(alpha=0.25)
plt.tight_layout()
plt.savefig("03_year_trend.png", dpi=200)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt


fig, axes = plt.subplots(1, 3, figsize=(15, 5))
for ax, col in zip(axes, ["Fuel_Type", "Seller_Type", "Transmission"]):
    avg = df.groupby(col)["Selling_Price"].mean().sort_values(ascending=False)
    ax.bar(avg.index.astype(str), avg.values)
    ax.set_title("Avg Price by " + col.replace("_", " "))
    ax.set_ylabel("Selling Price (lakh)")
    ax.tick_params(axis="x", rotation=20)
fig.tight_layout()
plt.savefig("04_category_comparison.png", dpi=200)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt



plt.figure(figsize=(9, 5.5))
for transmission, g in df.groupby("Transmission"):
    plt.scatter(g["Kms_Driven"], g["Selling_Price"], label=transmission, s=35)
r = df["Kms_Driven"].corr(df["Selling_Price"])
plt.title(f"Kilometers Driven vs Selling Price (r = {r:.2f})")
plt.xlabel("Kilometers Driven")
plt.ylabel("Selling Price (lakh)")
plt.legend()
plt.tight_layout()
plt.savefig("05_kms_vs_selling.png", dpi=200)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt


corr = df[["Year", "Selling_Price", "Present_Price", "Kms_Driven", "Owner"]].corr()
fig, ax = plt.subplots(figsize=(8, 6))
im = ax.imshow(corr, cmap="coolwarm", vmin=-1, vmax=1)
fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
ax.set_xticks(range(len(corr.columns)), corr.columns, rotation=30, ha="right")
ax.set_yticks(range(len(corr.columns)), corr.columns)
for i in range(len(corr)):
    for j in range(len(corr)):
        ax.text(j, i, f"{corr.iloc[i,j]:.2f}", ha="center", va="center")
ax.set_title("Correlation Matrix")
fig.tight_layout()
plt.savefig("06_correlation_heatmap.png", dpi=200)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

df['Present_Price'].hist(bins=15)
plt.title('Distribution of Present Price')
plt.xlabel('Present Price in Lakhs')
plt.ylabel('No. of cars')
plt.savefig('07_present_price_hist.png')
plt.show()
plt.close()

df['Kms_Driven'].hist(bins=15)
plt.title('Distribution of Kms Driven')
plt.xlabel('Kms Driven')
plt.ylabel('No. of cars')
plt.savefig('08_kms_driven_hist.png')
plt.show()
plt.close()